name: Manual File Collate
on:
  workflow_dispatch:
  schedule:
  - cron: "0 1 * * *"
  
jobs:
  Manual:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: rocker/tidyverse:4.2
    steps:
      - run: git config --system --add safe.directory '*'
      
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Run automated collation files
        run: |
          R -e 'remotes::install_version("pacman", version = "0.5.1")'
          Rscript $GITHUB_WORKSPACE/Scripts/automation_collate_script.R

      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add current_files/*
          git commit -m "Updating Manual Files" || echo "No changes to commit"
          git push https://${GITHUB_PAT}:${GITHUB_PAT}@github.com/${GITHUB_REPOSITORY} 
          
